CREATE TABLE NA_FAQ_FORM_TAG (
				ID                       INTEGER NOT NULL,
				ID_NA_GESTAO             INTEGER NOT NULL,
				NOME_FORMULARIO          VARCHAR(255) NOT NULL,
				TAGS                     VARCHAR(255) NOT NULL,
				DATA_HORA_ALTERACAO      TIMESTAMP NOT NULL,
				ID_NA_USUARIO_AUDITORIA  INTEGER,
				ID_NA_SISTEMA_AUDITORIA  INTEGER,
				CONSTRAINT PK_NA_FAQ_FORM_TAG PRIMARY KEY (ID),
				CONSTRAINT UNQ_NA_FAQ_FORM_TAG UNIQUE (ID_NA_GESTAO, NOME_FORMULARIO),
				CONSTRAINT FK_NA_FAQ_FORM_TAG_GESTAO FOREIGN KEY (ID_NA_GESTAO) REFERENCES NA_GESTAO (ID) ON UPDATE CASCADE);